### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by Karllas** [mallman/CoreMLaMa#4]
When model is exported in FP16 and ran on iOS device the output is randomly wrong. Attaching image, mask and output
![IMG_9864](https://github.com/mallman/CoreMLaMa/assets/28707155/f6edcda5-5e7a-42de-8c7d-55f44cb7f96d)
![IMG_9866](https://github.com/mallman/CoreMLaMa/assets/28707155/53472ca8-3f84-4bad-b825-2972fe3cc162)
![IMG_9865](https://github.com/mallman/CoreMLaMa/assets/28707155/9e557630-193c-4ed5-af9b-6d9de1fcf0b5)

**Comment by mallman** [comment]
Hi @Karllas.

Thank you for your report. Unfortunately I don't have a good answer for you.

I have not personally tested or attempted to run this model on an iOS device. I've only run this model on macOS.

Other people have reported similarly unacceptable results from running the converted model on iOS, such as unacceptably high memory usage. If you look at the closed issues for this repo you'll see what I mean.

I'm going to update this project's readme to elaborate on the deployment considerations for this model.
