### ISSUE TITLE
Can help for MI-Gan to CoreML?

### ISSUE THREAD

**Issue by LONGDDSF** [mallman/CoreMLaMa#5]
Using your python script, I also successfully converted to coreml model, but I found that the memory was very high when the phone was running, I guess it has something to do with the model, it is 200M, I found there is MI-GAN model in iopaint, May I ask if you have tried it, and how to convert it to coreML?

**Comment by mallman** [comment]
I have not tried MI-GAN. It looks like it would be more complicated to port to CoreML. I'm sorry I can't provide specific guidance on porting it.
